&sv 54 c:\paraiba\sisinf12\planos~1
&sv 72 0
&sv 73 "-786111.06300 -706554.31300 5773919 10184193" 
&sv 76 
editc C:\PARAIBA\GESTIN\CAPLLU
&sv 61 C:\PARAIBA\GESTIN\CAPLLU
&sv 65 NONE
editc C:\PARAIBA\GESTIN\CAPLLU
editf NONE
&sv 69 C:\PARAIBA\GESTIN\CAPLLU
&sv 70 NONE
mape -786111.06300 -706554.31300 5773919 10184193
drawe arc OFF node OFF label ON tic OFF anno OFF
setd 5
setd ON
backe arc ON node OFF label OFF tic OFF anno OFF
backc C:\PARAIBA\SISINF12\PLANOS~1\BACIA 2
&sv 87 2
annotype POINT1
annopos LL
annofit OFF
annolevel 1
annosym 1
annosize 0
annoit KEYBOARD
duplicatearcs YES
arctype LINE
setangle 0
&sv 86 
lineset C:\PROGRA~1\ARCEXE\SYMBOLS\COLOR.LIN
markerset C:\PROGRA~1\ARCEXE\SYMBOLS\COLOR.MRK
textset C:\PROGRA~1\ARCEXE\SYMBOLS\PLOTTER.TXT
win pos w t    140   272   652   331
win pos w g     44    44   780   576
win pos w 2     52   118   118   281
